---
- name: Cleanup
  hosts: localhost
  connection: local
  gather_facts: false
  no_log: "{{ molecule_no_log }}"
  tasks:

    - name: Remove secret if it exists
      kubernetes.core.k8s:
        state: absent
        api_version: v1
        kind: Secret
        name: mysecret
        namespace: mytest
