---
- name: Converge
  hosts: all

  vars_files:
    - vars/molecule.yml

  collections:
    - bparry02.k8s_app_development

  tasks:
    - name: "Include deploy_key_secret"
      include_role:
        name: deploy_key_secret
      vars:
        deploy_key_filename: "{{ lookup('env', 'KEY_FILE') }}"
        deploy_key_secret_namespace: "{{ molecule_namespace }}"
