---
dependency:
  name: galaxy
  enabled: False
driver:
  name: delegated
  options:
    managed: false
    ansible_connection_options:
      ansible_connection: local
      # set interpreter path to env variable set in GitHub workflow
      ansible_python_interpreter: ${ANSIBLE_PYTHON_INTERPRETER}
      # for local development in a venv
      #ansible_python_interpreter: ${MOLECULE_PROJECT_DIRECTORY}/bin/python
platforms:
  - name: localhost
provisioner:
  name: ansible
verifier:
  name: ansible
