---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  gather_facts: false

  tasks:
    - name: Get Secret
      kubernetes.core.k8s_info:
        api_version: v1
        kind: Secret
        name: mysecret
        namespace: mytest
      register: mysecret_content

    - name: print secret
      debug:
        var: mysecret_content

    - name: verify one secret found
      assert:
        that: mysecret_content.resources | length == 1
        fail_msg: "expected one secret but was {{ mysecret_content.resources | length }}"
