name: Ansible collection

on: [push]

jobs:
  test:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        #python-version: [3.6, 3.7, 3.8, 3.9]
        python-version: [3.8]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          echo PATH=$PATH
          echo "Python path: $(which python)"
          python -m pip install --upgrade pip setuptools
          pip install -r requirements.in
          pip list
      - uses: engineerd/setup-kind@v0.5.0
      - name: Test with molecule
        run: |
          # prepare k8s environment
          kubectl cluster-info
          kubectl create namespace mytest
          # test
          make test